// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CaptureState {
    "type": string;
    "recording": boolean;
    "tabs": number;
    "browser": string;
}

export interface CapturedRequest {
    "type": string;
    "id": string;
    "method": string;
    "url": string;
    "requestHeaders": { [_ in string]?: string } | null;
    "requestBody": string;
    "status": number;
    "statusText": string;
    "responseHeaders": { [_ in string]?: string } | null;
    "responseBody": string;
    "durationMs": number;
    "startedAt": number;
    "tabId": number;
    "tabTitle": string;
    "tabURL": string;
    "favIconUrl": string;
    "hasTiming"?: boolean;
    "waitMs"?: number;
    "downloadMs"?: number;
}
