// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CaptureState is what the extension says about itself. Paused is the extension's own fact and not
 * something the app can read off the other fields: a paused capture and a connected extension with
 * no tab under it look the same — nothing recorded, nothing to count.
 */
export interface CaptureState {
    "type": string;
    "recording": boolean;
    "paused": boolean;
    "tabs": number;
    "browser": string;

    /**
     * TabList is what Tabs counts, one entry each: which tabs are under capture and since when. It is
     * a second field rather than a richer Tabs because a frame already on the wire is a promise: an
     * app that is one version behind reads the count and knows no better, and a window that knows the
     * times can say since when.
     */
    "tabList"?: TabState[] | null;
}

/**
 * TabState is one tab under capture. Since is unix milliseconds, the moment the tab was armed — not
 * the time of its first request, which is a different and much later thing.
 */
export interface TabState {
    "tabId": number;
    "since": number;
}
