// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CaptureState {
    "type": string;
    "recording": boolean;
    "tabs": number;
    "browser": string;
}
