// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one line worth importing. Secret is a guess from the name, and the user confirms or
 * flips it in the dialog — it is never a statement about the value.
 */
export interface Entry {
    "name": string;
    "value": string;
    "secret": boolean;
}
