// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is the wire shape the frontend reads for the update events and the About window.
 */
export interface Info {
    "available": boolean;
    "current": string;
    "latest": string;

    /**
     * When the check that produced this ran, in ms since the epoch; zero if none ever has.
     */
    "checkedAt"?: number;
}
