// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * Changed is what a window receives when the workspace on screen moves.
 */
export interface Changed {
    "workspace": domain$0.Workspace;
}

/**
 * CreateInput is what the create card sends. There is no kind: a workspace made here is a personal
 * one — the schema has told the two apart from the start, and the form that makes a team is the one
 * that will also have to invite its first members.
 */
export interface CreateInput {
    "name": string;
    "color": string;
}

/**
 * Patch is a partial change: a nil field is left as it is.
 */
export interface Patch {
    "name"?: string | null;
    "color"?: string | null;
}
