// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * ImportReport says what an import did, so the screen can mention it once and the log keeps it.
 */
export interface ImportReport {
    "environments": number;
    "variables": number;
    "secrets": number;
    "warnings"?: string[] | null;

    /**
     * Completed is false when the import had already run, or has nothing to read.
     */
    "completed": boolean;
}

/**
 * Patch is a partial update: a nil field is left as it is.
 */
export interface Patch {
    "Name": string | null;
    "Color": string | null;
    "Readonly": boolean | null;
}

/**
 * VariablePatch edits one variable. SetValue is what keeps a secret's value when only its name or
 * its enabled flag is being changed: the sheet never has the old value to send back.
 */
export interface VariablePatch {
    "ID": string;
    "Name": string;
    "Kind": domain$0.VariableKind;
    "Enabled": boolean;
    "Value": string;
    "SetValue": boolean;
}
