// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * EnvironmentPatch is a partial update: a nil field is left as it is.
 */
export interface EnvironmentPatch {
    "name"?: string | null;
    "color"?: string | null;
    "readonly"?: boolean | null;
}

/**
 * ImportReport says what an import did, so the screen can mention it once and the log keeps it.
 */
export interface ImportReport {
    "environments": number;
    "variables": number;
    "secrets": number;
    "warnings"?: string[] | null;

    /**
     * Completed is false when the import had already run, or has nothing to read.
     */
    "completed": boolean;
}

/**
 * VariableDraft is a variable on its way in: the sheet's "add row" leaves it empty, the .env
 * dialog fills it in, and both go through one call.
 */
export interface VariableDraft {
    "name": string;
    "kind": domain$0.VariableKind;
    "value"?: string;
}

/**
 * VariablePatch edits one variable. SetValue is what keeps a secret's value when only its name or
 * its enabled flag is being changed: the sheet never has the old value to send back.
 */
export interface VariablePatch {
    "id": string;
    "name": string;
    "kind": domain$0.VariableKind;
    "enabled": boolean;
    "value"?: string;
    "setValue": boolean;
}
