// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * The reader knows one of them; the writer knows all five.
 */
export enum CommandFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormatCurl = "curl",
    FormatFetch = "fetch",
    FormatWget = "wget",
    FormatHTTPie = "httpie",
    FormatPowerShell = "powershell",
};

/**
 * CommandKind is what reading the text came to.
 */
export enum CommandKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindNone = "none",
    KindOK = "ok",
    KindError = "error",
};

/**
 * CommandReason is why a command was recognised but could not be read. These cross to the window,
 * which has a sentence for each, so the values are a contract with the locale files rather than a
 * name for anything on this side.
 */
export enum CommandReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReasonNoURL = "no-url",
    ReasonBadQuotes = "bad-quotes",
    ReasonLeftover = "leftover",
    ReasonUnsupportedMultipart = "unsupported-multipart",
};

/**
 * KindNone is "not a command at all, leave the field alone", which is what most pastes come to;
 * KindError carries the reason the window phrases. A command that was read is a Seed — the same
 * whole request "Open in Request" produces.
 */
export interface CommandResult {
    "kind": CommandKind;
    "seed": Seed;
    "reason": CommandReason;
}

/**
 * Paste is a pasted command applied to the draft: what the reading came to, and the draft as it
 * stands when there turned out to be something to replace it with. State is absent for the pastes
 * that were not commands at all, which is most of them.
 */
export interface Paste {
    "reading": CommandResult;
    "state"?: State | null;
}

/**
 * Preview is what the command line cannot work out from the draft alone: which of its `{{tokens}}`
 * mean nothing. There is no verdict here — the rest follows from this and a URL the window holds.
 */
export interface Preview {
    "missing": string[] | null;
}

/**
 * RowPatch is an edit to one row. Each field is optional, because a patch says what changed and
 * nothing else: a row sent whole would undo a keystroke that landed between the two.
 */
export interface RowPatch {
    "name"?: string | null;
    "value"?: string | null;
    "enabled"?: boolean | null;
    "domain"?: string | null;
    "expires"?: string | null;
    "secure"?: boolean | null;
    "httpOnly"?: boolean | null;

    /**
     * Src and File belong to a form row: the path a file field carries, and whether it is one.
     */
    "src"?: string | null;
    "file"?: boolean | null;
}

/**
 * Seed is a whole request handed to the draft: what "Open in Request" and a pasted command both
 * produce. Headers are pairs because a request can carry the same name twice.
 */
export interface Seed {
    "method": string;
    "url": string;
    "body": string;

    /**
     * A seed carries the format too: a followed link or a pasted command is a whole request, and the
     * Content-Type that follows from the kind is part of what it goes out with.
     */
    "bodyKind"?: domain$0.BodyKind;
    "form"?: domain$0.FormRow[] | null;
    "bodyFile"?: string;

    /**
     * A seed may carry neither list: a followed link has headers and no jar, a pasted command may
     * have neither. `omitempty` is what says so on the wire.
     */
    "headers"?: domain$0.HeaderPair[] | null;
    "cookies"?: domain$0.CookieRow[] | null;

    /**
     * Auth is what the request authorizes itself with. It travels resolved: whoever builds a seed
     * knows where the request came from, and a seed is a request, not a place in a tree.
     */
    "auth"?: domain$0.Auth | null;
}

/**
 * State is the draft as it stands, with the preview that follows from it. Every answer carries
 * both, so the window never has to ask what changed — and never has to work out for itself whether
 * what it holds can go out.
 */
export interface State {
    "draft": domain$0.Draft;
    "preview": Preview;

    /**
     * Projected is what the authorization puts in the parameter and header lists, which is not part
     * of the draft and is not stored with it: it is what the draft's auth comes to, worked out on
     * every answer so the two can never disagree.
     */
    "projected": domain$0.ProjectedRow[] | null;

    /**
     * Token is the state of a credential somebody else issues, for the schemes that have one. It is
     * absent for a scheme that carries what it was given: there is nothing to say about a token the
     * user typed, and a block saying so would be noise.
     */
    "token"?: domain$0.AuthToken | null;

    /**
     * Inherited is what the levels above this draft answer with, for a draft that is a node of a
     * tree: the nearest one that gave a credential, or nothing when none did. It is not a getter the
     * window could have written for itself — «None» on a folder is a level the walk goes past, and
     * that rule belongs with the walk.
     */
    "inherited"?: domain$0.Auth | null;
}

/**
 * TextField names one of the two texts the window owns while they are being typed in. Everything
 * else about the draft is edited a row at a time, by id.
 */
export enum TextField {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FieldURL = "url",
    FieldBody = "body",
};

/**
 * TextInput is a buffer flush. Rev is the window's own counter, and it comes back with the answer:
 * a reply to a keystroke that has since been typed over is recognised by it and dropped.
 */
export interface TextInput {
    "field": TextField;
    "text": string;
    "rev": number;
}

/**
 * TextResult is a buffer's answer. It carries back which buffer it is and the revision the window
 * sent with it: a reply to a keystroke that has since been typed over is recognised by those two
 * and dropped. The text itself is not in the answer — it is the window's until the window says
 * otherwise, and an answer that overwrote it would be a character lost under the caret.
 */
export interface TextResult {
    "field": TextField;
    "rev": number;
    "draft": domain$0.Draft;
    "preview": Preview;

    /**
     * Projected is what the authorization puts in the parameter and header lists, which is not part
     * of the draft and is not stored with it: it is what the draft's auth comes to, worked out on
     * every answer so the two can never disagree.
     */
    "projected": domain$0.ProjectedRow[] | null;

    /**
     * Token is the state of a credential somebody else issues, for the schemes that have one. It is
     * absent for a scheme that carries what it was given: there is nothing to say about a token the
     * user typed, and a block saying so would be noise.
     */
    "token"?: domain$0.AuthToken | null;

    /**
     * Inherited is what the levels above this draft answer with, for a draft that is a node of a
     * tree: the nearest one that gave a credential, or nothing when none did. It is not a getter the
     * window could have written for itself — «None» on a folder is a level the walk goes past, and
     * that rule belongs with the walk.
     */
    "inherited"?: domain$0.Auth | null;
}
