// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * Preview is what the command line draws and cannot work out from the draft alone: which of its
 * `{{tokens}}` mean nothing. Whether the request can go out follows from that and from a URL the
 * window itself is holding, so there is no verdict here — only what the window cannot see for
 * itself.
 */
export interface Preview {
    "missing": string[] | null;
}

/**
 * RowPatch is an edit to one row. Each field is optional, because a patch says what changed and
 * nothing else: a row sent whole would undo a keystroke that landed between the two.
 */
export interface RowPatch {
    "name"?: string | null;
    "value"?: string | null;
    "enabled"?: boolean | null;
    "domain"?: string | null;
    "expires"?: string | null;
    "secure"?: boolean | null;
    "httpOnly"?: boolean | null;
}

/**
 * Seed is a whole request handed to the draft: what "открыть в запросе" and a pasted command both
 * produce. Headers are pairs because a request can carry the same name twice.
 */
export interface Seed {
    "method": string;
    "url": string;
    "body": string;

    /**
     * A seed may carry neither list: a followed link has headers and no jar, a pasted command may
     * have neither. `omitempty` is what says so on the wire.
     */
    "headers"?: domain$0.HeaderPair[] | null;
    "cookies"?: domain$0.CookieRow[] | null;

    /**
     * Auth is what the request authorizes itself with. It travels resolved: whoever builds a seed
     * knows where the request came from, and a seed is a request, not a place in a tree.
     */
    "auth"?: domain$0.Auth | null;
}

/**
 * State is the draft as it stands, with the preview that follows from it. Every answer carries
 * both, so the window never has to ask what changed — and never has to work out for itself whether
 * what it holds can go out.
 */
export interface State {
    "draft": domain$0.Draft;
    "preview": Preview;
}

/**
 * TextField names one of the two texts the window owns while they are being typed in. Everything
 * else about the draft is edited a row at a time, by id.
 */
export enum TextField {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FieldURL = "url",
    FieldBody = "body",
};

/**
 * TextInput is a buffer flush. Rev is the window's own counter, and it comes back with the answer:
 * a reply to a keystroke that has since been typed over is recognised by it and dropped.
 */
export interface TextInput {
    "field": TextField;
    "text": string;
    "rev": number;
}

/**
 * TextResult is a buffer's answer. It carries back which buffer it is and the revision the window
 * sent with it: a reply to a keystroke that has since been typed over is recognised by those two
 * and dropped. The text itself is not in the answer — it is the window's until the window says
 * otherwise, and an answer that overwrote it would be a character lost under the caret.
 */
export interface TextResult {
    "field": TextField;
    "rev": number;
    "draft": domain$0.Draft;
    "preview": Preview;
}
