// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as updater$0 from "../../../../../json-inspector/internal/infra/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as bridge$0 from "../../../../../json-inspector/internal/transport/bridge/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as settings$0 from "../../../../../json-inspector/internal/usecase/settings/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "capture-disconnected": void;
            "capture-state": bridge$0.CaptureState;
            "captured-request": bridge$0.CapturedRequest;
            "open-tab": number;
            "settings:theme": settings$0.ThemeChanged;
            "update-available": updater$0.Info | null;
            "update-check": void;
        }
    }
}
