// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as domain$0 from "../../../../../json-inspector/internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as updater$0 from "../../../../../json-inspector/internal/infra/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as bridge$0 from "../../../../../json-inspector/internal/transport/bridge/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as collection$0 from "../../../../../json-inspector/internal/usecase/collection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as record$0 from "../../../../../json-inspector/internal/usecase/record/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as settings$0 from "../../../../../json-inspector/internal/usecase/settings/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "capture-disconnected": void;
            "capture-state": bridge$0.CaptureState;
            "collection:run-finished": domain$0.CollectionRun;
            "collection:run-progress": collection$0.RunProgress;
            "open-tab": number;
            "record:added": domain$0.Record;
            "request:failed": record$0.RequestFailed;
            "request:finished": record$0.RequestFinished;
            "settings:language": settings$0.LanguageChanged;
            "settings:theme": settings$0.ThemeChanged;
            "update-available": updater$0.Info | null;
            "update-check": void;
        }
    }
}
