// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * HistoryCleared says whose history went, because every open window has to decide whether the
 * list it draws is the one that was cleared.
 */
export interface HistoryCleared {
    "workspaceId": string;
    "removed": number;
}

/**
 * IngestInput is a request this app did not send. An empty Source means the browser — the
 * extension is the only thing that reports one from the outside.
 */
export interface IngestInput {
    "source": domain$0.RecordSource;
    "method": string;
    "url": string;
    "status": number;
    "statusText": string;
    "contentType"?: string;
    "requestHeaders": domain$0.HeaderPair[] | null;
    "responseHeaders": domain$0.HeaderPair[] | null;
    "requestBody": string;
    "responseBody": string;
    "durationMs": number;

    /**
     * Everything below only exists for a record that came from a browser tab. `omitempty` is what
     * says so on the wire, so a caller with no tab names none of them instead of spelling out zeros.
     */
    "startedAt"?: number;
    "waitMs"?: number;
    "downloadMs"?: number;
    "tabId"?: number;
    "tabTitle"?: string;
    "tabURL"?: string;
    "favIconUrl"?: string;
}

/**
 * RequestFailed is an attempt that produced no record at all, which is a failure of this side
 * rather than of the network: a request that never reached the server still has a record.
 */
export interface RequestFailed {
    "id": string;
    "error": string;

    /**
     * Failure is the same news in the window's terms — the code and the values its sentence needs —
     * when the app is the side that refused. An error from the network has none, and the window shows
     * the message beside it.
     */
    "failure"?: domain$0.Failure | null;
}

/**
 * RequestFinished carries the record the attempt produced, in the same shape history lists.
 */
export interface RequestFinished {
    "id": string;
    "record": domain$0.Record;
}
