// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * Level is one step of a chain: a collection, a folder or a request, and what it runs.
 */
export interface Level {
    "nodeId": string;
    "name": string;
    "kind": string;
    "scripts": domain$0.Scripts;
}
