// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails service backing the whole UI.
 * Its exported methods are callable from the frontend through the generated bindings.
 * 
 * In v3 a service is a singleton shared by every window (the main window today,
 * the environment editor later), so anything mutable lives under mu.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BridgePort returns the loopback port the browser extension connects to, so
 * the empty state can name it without hardcoding the number in the template.
 */
export function BridgePort(): $CancellablePromise<number> {
    return $Call.ByID(3557041683);
}

/**
 * CancelRequest cancels the in-flight HTTP request, if any.
 */
export function CancelRequest(): $CancellablePromise<void> {
    return $Call.ByID(980174012);
}

/**
 * CheckForUpdates queries the registry immediately and reports the result.
 */
export function CheckForUpdates(): $CancellablePromise<update$0.Update | null> {
    return $Call.ByID(2675659504);
}

/**
 * Fetch performs a GET request; used to follow related and pagination links.
 * The headers of the request being followed are carried over (e.g. auth).
 */
export function Fetch(url: string, headers: { [_ in string]?: string } | null): $CancellablePromise<$models.ResponseResult | null> {
    return $Call.ByID(4196614347, url, headers);
}

/**
 * Name returns the display name, which the frontend draws in its title bar and
 * About window.
 */
export function Name(): $CancellablePromise<string> {
    return $Call.ByID(257522798);
}

/**
 * PauseCapture tells the extension to stop capturing every tab. It is the
 * "Приостановить перехват" action in the browser view; the extension stops its
 * interceptors and replies with a fresh capture-state message.
 */
export function PauseCapture(): $CancellablePromise<void> {
    return $Call.ByID(2598102529);
}

/**
 * ResumeCapture is the other half: the extension re-injects into the tabs it
 * had been recording before the pause.
 */
export function ResumeCapture(): $CancellablePromise<void> {
    return $Call.ByID(2781540432);
}

/**
 * SecretDelete removes one environment secret.
 */
export function SecretDelete(envID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1436352574, envID, name);
}

/**
 * SecretGet reads one environment secret; "" means nothing is stored.
 */
export function SecretGet(envID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1147717627, envID, name);
}

/**
 * SecretSet stores one environment secret.
 */
export function SecretSet(envID: string, name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2991470063, envID, name, value);
}

/**
 * SendRequest performs an HTTP request and returns the full result. It is used
 * by the manual request builder.
 */
export function SendRequest(method: string, url: string, headers: { [_ in string]?: string } | null, body: string): $CancellablePromise<$models.ResponseResult | null> {
    return $Call.ByID(482143032, method, url, headers, body);
}

/**
 * ShowAbout opens the About window, or focuses it if it is already open.
 * Bound to the frontend and wired to the native menu item.
 */
export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(2874201689);
}

/**
 * ToggleMaximize toggles the window zoom (double-click on the title bar).
 */
export function ToggleMaximize(): $CancellablePromise<void> {
    return $Call.ByID(963143607);
}

/**
 * UpdateNow downloads, verifies and installs the given version, then restarts.
 */
export function UpdateNow(version: string): $CancellablePromise<void> {
    return $Call.ByID(4106324996, version);
}

/**
 * Version returns the running version.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2431199839);
}
