// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BridgePort(): $CancellablePromise<number> {
    return $Call.ByID(3557041683);
}

export function CancelRequest(): $CancellablePromise<void> {
    return $Call.ByID(980174012);
}

export function CheckForUpdates(): $CancellablePromise<update$0.Update | null> {
    return $Call.ByID(2675659504);
}

export function Fetch(url: string, headers: { [_ in string]?: string } | null): $CancellablePromise<$models.ResponseResult | null> {
    return $Call.ByID(4196614347, url, headers);
}

export function Name(): $CancellablePromise<string> {
    return $Call.ByID(257522798);
}

export function PauseCapture(): $CancellablePromise<void> {
    return $Call.ByID(2598102529);
}

export function ResumeCapture(): $CancellablePromise<void> {
    return $Call.ByID(2781540432);
}

export function SecretDelete(envID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1436352574, envID, name);
}

export function SecretGet(envID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1147717627, envID, name);
}

export function SecretSet(envID: string, name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2991470063, envID, name, value);
}

export function SendRequest(method: string, url: string, headers: { [_ in string]?: string } | null, body: string): $CancellablePromise<$models.ResponseResult | null> {
    return $Call.ByID(482143032, method, url, headers, body);
}

/**
 * ShowAbout opens the About window, or focuses it if it is already open.
 * Bound to the frontend and wired to the native menu item.
 */
export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(2874201689);
}

export function ToggleMaximize(): $CancellablePromise<void> {
    return $Call.ByID(963143607);
}

export function UpdateNow(version: string): $CancellablePromise<void> {
    return $Call.ByID(4106324996, version);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2431199839);
}
