// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BridgePort(): $CancellablePromise<number> {
    return $Call.ByID(3557041683);
}

/**
 * Build is the CI run number, empty for local builds.
 */
export function Build(): $CancellablePromise<string> {
    return $Call.ByID(504336667);
}

export function CancelRequest(): $CancellablePromise<void> {
    return $Call.ByID(980174012);
}

/**
 * CheckForUpdates answers the About window's own check. A release it finds is also announced to
 * the main window, so the status bar's link appears without waiting for the next launch — the
 * one place a manual check and the startup check have to agree.
 */
export function CheckForUpdates(): $CancellablePromise<update$0.Info | null> {
    return $Call.ByID(2675659504);
}

export function Fetch(url: string, headers: { [_ in string]?: string } | null): $CancellablePromise<$models.Response | null> {
    return $Call.ByID(4196614347, url, headers);
}

export function Name(): $CancellablePromise<string> {
    return $Call.ByID(257522798);
}

export function PauseCapture(): $CancellablePromise<void> {
    return $Call.ByID(2598102529);
}

/**
 * RequestUpdateCheck reuses or opens the About window and asks it to run a check. The request
 * is parked as well as sent, because only the About window listens for it here — and a window
 * that is being created right now has no listeners yet. It picks the parked request up on mount.
 * 
 * The flag is cleared by TakeUpdateCheckRequest alone, never here: that is what makes the two
 * paths deliver exactly one check between them, however they interleave.
 */
export function RequestUpdateCheck(): $CancellablePromise<void> {
    return $Call.ByID(2320128613);
}

export function ResumeCapture(): $CancellablePromise<void> {
    return $Call.ByID(2781540432);
}

export function SecretDelete(envID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1436352574, envID, name);
}

export function SecretGet(envID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1147717627, envID, name);
}

export function SecretSet(envID: string, name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2991470063, envID, name, value);
}

export function SendRequest(method: string, url: string, headers: { [_ in string]?: string } | null, body: string): $CancellablePromise<$models.Response | null> {
    return $Call.ByID(482143032, method, url, headers, body);
}

/**
 * Bound to the frontend and to the native About menu item.
 */
export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(2874201689);
}

/**
 * TakeUpdateCheckRequest reports and clears a request parked by RequestUpdateCheck. Destructive
 * on purpose: it is called from both the mount and the event handler, and only the first caller
 * may act on it, or an old request would fire a check the next time the window opens.
 */
export function TakeUpdateCheckRequest(): $CancellablePromise<boolean> {
    return $Call.ByID(939177566);
}

export function ToggleMaximize(): $CancellablePromise<void> {
    return $Call.ByID(963143607);
}

export function UpdateNow(version: string): $CancellablePromise<void> {
    return $Call.ByID(4106324996, version);
}

/**
 * UpdateStatus is what the last check saw, without touching the network.
 */
export function UpdateStatus(): $CancellablePromise<update$0.Info | null> {
    return $Call.ByID(1098431686);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2431199839);
}
