// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Response is what a request comes back as: the body plus the per-phase timings.
 */
export interface Response {
    "status": number;
    "statusText": string;
    "headers": { [_ in string]?: string } | null;
    "body": string;
    "durationMs": number;
    "contentType": string;
    "error"?: string;
    "cancelled"?: boolean;
    "dnsMs"?: number;
    "connectMs"?: number;
    "tlsMs"?: number;
    "waitMs"?: number;
    "downloadMs"?: number;
}
