// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Update {
    "available": boolean;
    "current": string;
    "latest": string;
}
