// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is the wire shape the frontend reads for the update events and the modal.
 */
export interface Info {
    "available": boolean;
    "current": string;
    "latest": string;
}
