// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * NewNode is what the tree asks for when a row is created: where it goes, what it is, and the one
 * thing a new request already knows about itself — a method, because that is what the row draws.
 */
export interface NewNode {
    "collectionId": string;
    "parentId"?: string;
    "kind": domain$0.NodeKind;
    "name": string;
    "method"?: string;
}

/**
 * RunProgress is one request of a run finishing. The counters are here and not in the window: the
 * window that opened the collections view while a run was going would otherwise count from the
 * middle, and the request that just finished is a row it can draw at once.
 */
export interface RunProgress {
    "runId": string;
    "done": number;
    "total": number;
    "result": domain$0.CollectionRunResult;
}
