// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * NewNode is what the tree asks for when a row is created: where it goes, what it is, and the one
 * thing a new request already knows about itself — a method, because that is what the row draws.
 */
export interface NewNode {
    "collectionId": string;
    "parentId"?: string;
    "kind": domain$0.NodeKind;
    "name": string;
    "method"?: string;
}
