// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * NewNode is what the tree asks for when a row is created: where it goes, what it is, and what is
 * already known about the request. A request made by hand arrives with its method and nothing else —
 * the rest is filled in by the card that opens next — while one saved from the command line is a
 * whole request, and building it empty first would be a node with no address if the second step
 * failed.
 */
export interface NewNode {
    "collectionId": string;
    "parentId"?: string;
    "kind": domain$0.NodeKind;
    "name": string;
    "method"?: string;
    "url"?: string;
    "params"?: domain$0.Row[] | null;
    "headers"?: domain$0.Row[] | null;
    "body"?: string;
    "cookies"?: domain$0.CookieRow[] | null;
    "auth"?: domain$0.Auth | null;
}

/**
 * RunProgress is one request of a run finishing. The counters are here and not in the window: the
 * window that opened the collections view while a run was going would otherwise count from the
 * middle, and the request that just finished is a row it can draw at once.
 */
export interface RunProgress {
    "runId": string;

    /**
     * What the run was started from, so a window that has since looked at another level can tell
     * which run a row belongs to: it is the same pair the finished run carries.
     */
    "collectionId": string;
    "nodeId": string;
    "done": number;
    "total": number;
    "result": domain$0.CollectionRunResult;
}
