// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Format is the tool a command was written for. The same five are the export targets.
 */
export enum Format {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormatCurl = "curl",
    FormatFetch = "fetch",
    FormatWget = "wget",
    FormatHTTPie = "httpie",
    FormatPowerShell = "powershell",
};

/**
 * Header is one request header, name and value as written.
 */
export interface Header {
    "name": string;
    "value": string;
}

/**
 * Kind is what Parse made of the text.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindNone = "none",
    KindOK = "ok",
    KindError = "error",
};

/**
 * Reason is why a command was recognised but could not be read; the UI phrases these.
 */
export enum Reason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReasonNoURL = "no-url",
    ReasonBadQuotes = "bad-quotes",
    ReasonLeftover = "leftover",
    ReasonBadFetchInit = "bad-fetch-init",
    ReasonUnsupportedVariable = "unsupported-variable",
    ReasonUnsupportedField = "unsupported-field",
    ReasonUnsupportedMultipart = "unsupported-multipart",
};

/**
 * Request is a parsed command. Headers keep the order they were written in; a repeated name keeps
 * the position of its first occurrence and the value of its last, which is what the TS gets from
 * collapsing them into an object.
 */
export interface Request {
    "method": string;
    "url": string;
    "headers": Header[] | null;
    "body": string;

    /**
     * Auth is the credential the command carried, as the scheme it *is* rather than as the header it
     * comes to. `curl -u` and `-H 'Authorization: Basic …'` are the same request on the wire and
     * different things in the app: one is an answer the Auth chip can edit afterwards, the other a
     * header somebody wrote and meant to keep. Only flags become a scheme; a written header stays a
     * header, and being written it wins over any scheme anyway.
     */
    "auth"?: domain$0.Auth | null;
}

/**
 * Result is a parse outcome. KindNone means "not a command, leave the field alone"; KindError
 * carries the reason the UI phrases.
 */
export interface Result {
    "kind": Kind;
    "format": Format;
    "request": Request;
    "reason": Reason;
}
