// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService is the account as the window sees it: who the app is signed in as, the sign-in
 * itself, and the devices it is signed in on.
 * 
 * Every method answers the whole state rather than the piece that changed — a window drawing the
 * account wants one answer, not a puzzle of them — and every window is told as well, because the
 * settings window is not the only one that draws it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "../../usecase/account/models.js";

/**
 * Begin starts a sign-in: the server hands over a code, the browser opens on the page where it is
 * confirmed, and the answer comes back as an event — see TopicChanged. The call returns as soon as
 * there is a code to show, because waiting is the person's business and not the window's.
 */
export function Begin(server: string): $CancellablePromise<account$0.State> {
    return $Call.ByID(581741981, server);
}

/**
 * Cancel stops waiting for a code that nobody is going to confirm. The code itself lives on until
 * it runs out on its own: the app cannot call it back.
 */
export function Cancel(): $CancellablePromise<account$0.State> {
    return $Call.ByID(2155083938);
}

/**
 * DeleteAccount leaves the server for good. The collections on this machine stay: they were always
 * local, and leaving an account is not the same as erasing a drive.
 */
export function DeleteAccount(): $CancellablePromise<account$0.State> {
    return $Call.ByID(3455939062);
}

export function EndOthers(): $CancellablePromise<domain$0.Session[] | null> {
    return $Call.ByID(1387795706);
}

export function EndSession(sessionID: string): $CancellablePromise<domain$0.Session[] | null> {
    return $Call.ByID(3100749855, sessionID);
}

/**
 * Sessions is where else the account is signed in. It is a call to the server, so it can fail with
 * the server being away — which the window says in its own words rather than showing an empty list.
 */
export function Sessions(): $CancellablePromise<domain$0.Session[] | null> {
    return $Call.ByID(2376876357);
}

/**
 * SetServer remembers a server other than the one the app would use by default. It is kept even
 * when nobody is signed in, and it does not sign anybody out.
 */
export function SetServer(server: string): $CancellablePromise<account$0.State> {
    return $Call.ByID(713534067, server);
}

/**
 * SignOut forgets the account on this machine. It works with the server out of reach: this is a
 * local app, and being unable to reach anybody is not a reason to stay signed in.
 */
export function SignOut(): $CancellablePromise<account$0.State> {
    return $Call.ByID(189619987);
}

/**
 * State is what the settings window draws: nothing signed in, a sign-in in progress, or an account.
 */
export function State(): $CancellablePromise<account$0.State> {
    return $Call.ByID(2889015789);
}
