// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BridgeService is the extension endpoint as the app sees it: the port the empty state shows and
 * the pause switch the capture bar uses. What arrives on that socket is handled by an ingest, not
 * by a bound method — see ingest.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function PauseCapture(): $CancellablePromise<void> {
    return $Call.ByID(3364473398);
}

/**
 * Port is the port the extension connects to — the service is the bridge, so the name omits it.
 */
export function Port(): $CancellablePromise<number> {
    return $Call.ByID(2250383837);
}

export function ResumeCapture(): $CancellablePromise<void> {
    return $Call.ByID(2491159241);
}
