// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BridgeService is the extension endpoint as the app sees it: the port the empty state shows and
 * the pause switch the capture bar uses. What arrives on that socket is handled by an ingest, not
 * by a bound method — see ingest.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * ApplyCaptureFilters hands the extension the rules it filters by. The app stores them and this is
 * the delivery: a frame to whoever is connected now, and nothing to whoever is not — the window
 * sends this again on every state frame it receives, which is how an extension that has just
 * reconnected is told the rules it missed.
 */
export function ApplyCaptureFilters(filters: domain$0.CaptureFilters): $CancellablePromise<void> {
    return $Call.ByID(2309446651, filters);
}

/**
 * Listening is whether anything answers on that port. A port taken by something else — a second
 * copy of the app, most often — leaves capture off for the whole session, and the window has to be
 * able to say so instead of drawing an address that leads nowhere.
 */
export function Listening(): $CancellablePromise<boolean> {
    return $Call.ByID(1959680275);
}

export function PauseCapture(): $CancellablePromise<void> {
    return $Call.ByID(3364473398);
}

/**
 * Port is the port the extension connects to — the service is the bridge, so the name omits it.
 */
export function Port(): $CancellablePromise<number> {
    return $Call.ByID(2250383837);
}

export function ResumeCapture(): $CancellablePromise<void> {
    return $Call.ByID(2491159241);
}
