// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionsService is the saved requests. Every call that changes the tree answers with the whole
 * tree — a rename moves a row the list is already drawing. It holds the draft too, because a saved
 * request is edited as one.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as collection$0 from "../../usecase/collection/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Contents is what the collection page's table draws: the requests inside the collection that is
 * open, folders and all, with the address each of them goes to and the folder it sits in. The tree
 * carries no request payload, so the page asks for its own rows rather than making every tree read
 * heavier for one screen.
 */
export function Contents(id: string): $CancellablePromise<domain$0.LevelRow[] | null> {
    return $Call.ByID(3362458552, id);
}

/**
 * CreatedCollection is what making a collection answers with, and it is CreatedNode's shape for
 * CreatedNode's reason: the id has to come back from Go, because a lookup by name would find the
 * older row of the same name — and a folder is created inside another one as often as at the top.
 */
export function CreateCollection(name: string, description: string, parentID: string): $CancellablePromise<$models.CreatedCollection> {
    return $Call.ByID(2119561358, name, description, parentID);
}

export function CreateNode($in: collection$0.NodeDraft): $CancellablePromise<$models.CreatedNode> {
    return $Call.ByID(2020879810, $in);
}

export function Delete(id: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(1880484957, id);
}

/**
 * Describe writes what a collection is for — the line the overview draws above its tabs. Empty is
 * an answer there: the header then shows the placeholder that invites one.
 */
export function Describe(id: string, description: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(4022716643, id, description);
}

/**
 * Duplicate copies a node under a name the window composes: the suffix that says what the copy is
 * is a word, and words belong to the side that knows the language.
 */
export function Duplicate(id: string, suffix: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(1426855475, id, suffix);
}

/**
 * ExportFile writes a collection — or one request, when the id names one — into a file the user
 * picks. False is a cancelled dialog, not an error, and the window says nothing about it.
 */
export function ExportFile(title: string, id: string): $CancellablePromise<boolean> {
    return $Call.ByID(4114312118, title, id);
}

/**
 * ImportFile asks for a file and imports it; a nil tree is a cancelled dialog, not a failure.
 * Nothing is guessed: a file that is not a Postman collection is told so. When a second shape
 * arrives, the window will offer the shapes by name rather than read the file as one it is not.
 */
export function ImportFile(title: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(548291153, title);
}

/**
 * LastRun is what the overview draws when it opens, and nil when nothing has been run here yet.
 */
export function LastRun(collectionID: string, nodeID: string): $CancellablePromise<domain$0.CollectionRun | null> {
    return $Call.ByID(1189953743, collectionID, nodeID);
}

export function MoveCollection(id: string, parentID: string, position: number): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(2780926367, id, parentID, position);
}

/**
 * MoveNode and MoveCollection are what a drop in the tree calls. The position is an index in the
 * level the row was dropped into, counted the way the window drew it — the requests of a collection
 * and the collections inside it are one list on screen and one number line here.
 */
export function MoveNode(id: string, collectionID: string, position: number): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(2249490431, id, collectionID, position);
}

/**
 * Node is what opening a saved request needs: a tree row carries its method and nothing else.
 */
export function Node(id: string): $CancellablePromise<domain$0.CollectionNode> {
    return $Call.ByID(2008168702, id);
}

/**
 * OpenNode puts a saved request into the draft its card edits, and answers with everything the card
 * draws. Opening is what a save starts over from as well: a draft that has just been opened has
 * nothing unsaved in it, which is where the window's "Unsaved" comes from and goes.
 */
export function OpenNode(id: string): $CancellablePromise<$models.NodeEditor> {
    return $Call.ByID(1109881158, id);
}

export function Rename(id: string, name: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(3088890764, id, name);
}

/**
 * Run starts a collection or a folder and answers with the id of the run. What happens next arrives
 * as events: a run of fifty requests outlives the call that started it, and the window draws it as
 * it goes.
 */
export function Run(collectionID: string, nodeID: string): $CancellablePromise<string> {
    return $Call.ByID(3708031267, collectionID, nodeID);
}

/**
 * SaveAuth writes what a collection authorizes its requests with. «None» is the same call with an
 * empty auth: a level that has none is a level the ones below it inherit past, and the overview
 * then draws the tab the way a collection without one looks.
 */
export function SaveAuth(id: string, auth: domain$0.Auth): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(3442193257, id, auth);
}

/**
 * SaveDraft copies what the command line is composing into a collection as a new request. The
 * draft is not touched: saving a copy is not a move. The request arrives whole, because the node
 * is written once — a second call filling in an empty one could leave it saved with no address.
 */
export function SaveDraft(collectionID: string, name: string): $CancellablePromise<$models.CreatedNode> {
    return $Call.ByID(1665422330, collectionID, name);
}

/**
 * SaveDraftToNew saves the command line's request as the first one of a collection that does not
 * exist yet, named by the caller. The sheet's «Создать «X»» row is one intention, and serving it in
 * two calls would leave an empty collection behind whenever the second one failed — a collection
 * nobody asked for, and one somebody then has to go and delete.
 * 
 * It is here rather than in the collection feature because the draft is: the request being composed
 * is this layer's to read, and the two calls that make one collection of it are this layer's to
 * join.
 */
export function SaveDraftToNew(collection: string, name: string): $CancellablePromise<$models.CreatedNode> {
    return $Call.ByID(1941657663, collection, name);
}

/**
 * SaveNode writes what the card is editing back into the tree. The draft is where the request is —
 * its method, its address, its rows, its body — and the node keeps what the card does not own: what
 * it is called, where it sits, when it was made.
 */
export function SaveNode(id: string): $CancellablePromise<$models.NodeEditor> {
    return $Call.ByID(867729327, id);
}

/**
 * SaveVariables writes the `{{tokens}}` a collection answers for the requests inside it. The set
 * arrives whole, as the editor holds it; the tree comes back because the panel draws these levels.
 */
export function SaveVariables(id: string, variables: domain$0.Variable[] | null): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(2342343120, id, variables);
}

/**
 * Stop ends the run after the request that is already in flight.
 */
export function Stop(): $CancellablePromise<boolean> {
    return $Call.ByID(3988284442);
}

export function Tree(): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(1137011870);
}
