// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionsService is the saved requests. Every call that changes the tree answers with the whole
 * tree, because a rename moves a row the list is already drawing — a caller that had to splice the
 * change in itself would be a second implementation of the tree's order.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as collection$0 from "../../usecase/collection/models.js";

export function CreateCollection(name: string, description: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(2119561358, name, description);
}

export function CreateNode($in: collection$0.NewNode): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(2020879810, $in);
}

export function Delete(id: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(1880484957, id);
}

export function Duplicate(id: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(1426855475, id);
}

/**
 * LastRun is what the overview draws when it opens, and nil when nothing has been run here yet.
 */
export function LastRun(collectionID: string, nodeID: string): $CancellablePromise<domain$0.CollectionRun | null> {
    return $Call.ByID(1189953743, collectionID, nodeID);
}

/**
 * Node is what opening a saved request needs: a tree row carries its method and nothing else.
 */
export function Node(id: string): $CancellablePromise<domain$0.CollectionNode> {
    return $Call.ByID(2008168702, id);
}

export function Rename(id: string, name: string): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(3088890764, id, name);
}

/**
 * Run starts a collection or a folder and answers with the id of the run. What happens next arrives
 * as events: a run of fifty requests outlives the call that started it, and the window draws it as
 * it goes.
 */
export function Run(collectionID: string, nodeID: string): $CancellablePromise<string> {
    return $Call.ByID(3708031267, collectionID, nodeID);
}

/**
 * SaveNode writes the request the card was editing back into the tree. Sending is a different
 * gesture: it does not save, and nothing here is called by it.
 */
export function SaveNode(node: domain$0.CollectionNode): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(867729327, node);
}

/**
 * Stop ends the run after the request that is already in flight.
 */
export function Stop(): $CancellablePromise<boolean> {
    return $Call.ByID(3988284442);
}

export function Tree(): $CancellablePromise<domain$0.Collection[] | null> {
    return $Call.ByID(1137011870);
}
