// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandService is the one half of the command boundary that does not belong to the draft:
 * writing a recorded request back out as a command a person can carry away. The other half —
 * reading a pasted command and handing it to the draft — is a draft call, because that is what it
 * does.
 * 
 * The rendering itself is a pure function of internal/usecase/draft. What cannot be done there is
 * done here: a command resolves `{{tokens}}` with a secret left masked, and the values that would
 * resolve it never reach the window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as draft$0 from "../../usecase/draft/models.js";

/**
 * Export writes a recorded request out as a command for one tool.
 */
export function Export(id: string, format: draft$0.CommandFormat): $CancellablePromise<string> {
    return $Call.ByID(2564897972, id, format);
}
