// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandService is the paste-and-copy pair: a command line read as a request, and a recorded
 * request written back as one.
 * 
 * Both halves are pure functions of internal/command — the package is the port of what used to live
 * in the window, kept honest by a corpus dumped from it. This service is where they are bound, and
 * where the one thing they cannot do alone is done for them: an export resolves `{{tokens}}` and
 * leaves a secret masked, and the values that would resolve it never reach the window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as command$0 from "../../command/models.js";

/**
 * Export writes a recorded request as a command for one tool. keepTokens is a snippet shared with
 * the tokens intact rather than the values they stand for, which is what a person pasting it into a
 * collection wants: the variables are resolved where the request is sent, not where it is copied.
 */
export function Export(id: string, format: command$0.Format, keepTokens: boolean): $CancellablePromise<string> {
    return $Call.ByID(2564897972, id, format, keepTokens);
}

/**
 * Parse reads a pasted command line. The answer is the parser's, whole: a text that is not a
 * command comes back as `none` rather than as a failure, because a person pasting an address into
 * the address field has done nothing wrong.
 */
export function Parse(text: string): $CancellablePromise<command$0.Result> {
    return $Call.ByID(3100254353, text);
}
