// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandService is the half of the command boundary that is not the draft: rendering a recorded
 * request as a command a person can carry away. The rendering itself is a pure function of
 * internal/usecase/draft; what cannot be done there is done here, because a command resolves
 * `{{tokens}}` with secrets left masked, and the values behind them never reach the window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as draft$0 from "../../usecase/draft/models.js";

/**
 * Export writes a recorded request out as a command for one tool.
 */
export function Export(id: string, format: draft$0.CommandFormat): $CancellablePromise<string> {
    return $Call.ByID(2564897972, id, format);
}
