// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DraftService is the request being composed. The window draws it and asks for changes; what those
 * changes mean — which rows a URL has, what a `{{token}}` resolves to, whether the request can go
 * out — is decided here.
 * 
 * Every call names the draft it is about: the command line's, or the node a card is editing. The
 * window holds both at once — switching between them must not lose the other — so nothing here
 * assumes there is one.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as draft$0 from "../../usecase/draft/models.js";

export function AddRow(id: domain$0.DraftID, kind: domain$0.RowKind): $CancellablePromise<draft$0.State> {
    return $Call.ByID(1330992221, id, kind);
}

export function PatchRow(draftID: domain$0.DraftID, kind: domain$0.RowKind, id: string, patch: draft$0.RowPatch): $CancellablePromise<draft$0.State> {
    return $Call.ByID(816954078, draftID, kind, id, patch);
}

/**
 * PickBodyFile asks the user for the file a body carries and answers with its path, or with nothing
 * when the dialog was closed — closing a dialog is not a failure.
 * 
 * Nothing is written into the draft here: the window patches the row the answer belongs to, the way
 * it patches a key or a value, so a pick travels as an edit and this answers only what was picked.
 */
export function PickBodyFile(title: string, kindName: string): $CancellablePromise<string> {
    return $Call.ByID(1983199931, title, kindName);
}

/**
 * RemoveRow and PatchRow address a row by id and not by position: a click that lands after the list
 * changed under it must not delete the row that took its place.
 */
export function RemoveRow(draftID: domain$0.DraftID, kind: domain$0.RowKind, id: string): $CancellablePromise<draft$0.State> {
    return $Call.ByID(4249851392, draftID, kind, id);
}

/**
 * Replace hands a draft a whole request: "открыть в запросе" on a record, or a command pasted into
 * the command line.
 */
export function Replace(id: domain$0.DraftID, seed: draft$0.Seed): $CancellablePromise<draft$0.State> {
    return $Call.ByID(2303442316, id, seed);
}

export function SetAuth(id: domain$0.DraftID, auth: domain$0.Auth): $CancellablePromise<draft$0.State> {
    return $Call.ByID(3062809258, id, auth);
}

/**
 * SetBodyFile is the path a Binary body will be read from. The dialog that produced it is
 * PickBodyFile below, and it is the window that decides which row the answer belongs to.
 */
export function SetBodyFile(id: domain$0.DraftID, path: string): $CancellablePromise<draft$0.State> {
    return $Call.ByID(3485419726, id, path);
}

/**
 * SetBodyKind picks the format the Body popover composes in. It is a call of its own rather than a
 * row patch because it is a property of the request and not of any one row.
 */
export function SetBodyKind(id: domain$0.DraftID, kind: domain$0.BodyKind): $CancellablePromise<draft$0.State> {
    return $Call.ByID(1227862282, id, kind);
}

export function SetMethod(id: domain$0.DraftID, method: string): $CancellablePromise<draft$0.State> {
    return $Call.ByID(2905225717, id, method);
}

/**
 * SetText is a buffer flush: the URL and the body are the window's while they are being typed, and
 * this is how they reach this side. The revision travels back with the answer so the window can
 * tell a reply to the keystroke it just made from one to the keystroke before it.
 */
export function SetText(id: domain$0.DraftID, $in: draft$0.TextInput): $CancellablePromise<draft$0.TextResult> {
    return $Call.ByID(819678171, id, $in);
}

/**
 * Snapshot is a draft as it stands, which is what a window opens on.
 */
export function Snapshot(id: domain$0.DraftID): $CancellablePromise<draft$0.State> {
    return $Call.ByID(2263784320, id);
}
