// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentsService is the environments screen and the request preview: the state they draw, the
 * edits they make, and the resolution a draft's `{{tokens}}` need until that moves to Go too.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dotenv$0 from "../../dotenv/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as environment$0 from "../../usecase/environment/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ActivateEnvironment(id: string): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(4240039849, id);
}

export function AddVariable(scope: domain$0.EnvScope, kind: domain$0.VariableKind): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(1119272004, scope, kind);
}

export function CreateEnvironment(name: string): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(586840570, name);
}

export function DeleteEnvironment(id: string): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2328245087, id);
}

export function ImportEntries(scope: domain$0.EnvScope, entries: dotenv$0.Entry[] | null): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2566995860, scope, entries);
}

/**
 * ImportLegacy moves what the old frontend kept in localStorage into the database, once. The
 * payload is the raw string: parsing the old shape is this side's job, not the window's.
 */
export function ImportLegacy(raw: string): $CancellablePromise<environment$0.ImportReport> {
    return $Call.ByID(3560788915, raw);
}

export function Missing(text: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(4257610239, text);
}

export function RemoveVariable(scope: domain$0.EnvScope, id: string): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2903571973, scope, id);
}

export function Resolve(name: string): $CancellablePromise<$models.ResolvedVariable> {
    return $Call.ByID(4211643035, name);
}

/**
 * Reveal is the eye button: the only call that hands a secret's value to the window.
 */
export function Reveal(id: string): $CancellablePromise<string> {
    return $Call.ByID(510563592, id);
}

export function SecretDelete(envID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(4292650974, envID, name);
}

export function SecretGet(envID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1721142299, envID, name);
}

export function SecretSet(envID: string, name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3564894735, envID, name, value);
}

/**
 * Snapshot is the whole screen. Secret values are not in it: a secret says it has one, and Reveal
 * is what shows it.
 */
export function Snapshot(): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2070616517);
}

/**
 * Substitute fills a text in with its variables; mask is what keeps a secret out of anything that
 * outlives the moment of sending.
 */
export function Substitute(text: string, mask: boolean): $CancellablePromise<string> {
    return $Call.ByID(4099133641, text, mask);
}

export function UpdateEnvironment(id: string, patch: environment$0.Patch): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2674046333, id, patch);
}

export function UpdateVariable(scope: domain$0.EnvScope, patch: environment$0.VariablePatch): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2299448532, scope, patch);
}
