// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentsService is the environments surface. Secrets are the only part of it that still
 * lives on this side: they sit in the OS keychain until the one-time import moves them into the
 * database, and this service is that import's read path as well as the UI's.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function SecretDelete(envID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(4292650974, envID, name);
}

export function SecretGet(envID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1721142299, envID, name);
}

export function SecretSet(envID: string, name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3564894735, envID, name, value);
}
