// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentsService is the environments screen: the state it draws and the edits it makes. What
 * a `{{token}}` resolves to is no longer the window's question — the draft asks that side of the
 * boundary itself, values and all.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dotenv$0 from "../../dotenv/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as environment$0 from "../../usecase/environment/models.js";

export function ActivateEnvironment(id: string): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(4240039849, id);
}

export function AddVariable(scope: domain$0.EnvScope, draft: environment$0.VariableDraft): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(1119272004, scope, draft);
}

/**
 * ClearGlobals empties the globals: they are one scope and cannot be deleted, only emptied.
 */
export function ClearGlobals(): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(265145458);
}

export function CreateEnvironment(draft: environment$0.EnvironmentDraft): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(586840570, draft);
}

export function DeleteEnvironment(id: string): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2328245087, id);
}

/**
 * EnsureDefaults seeds a fresh database with the environment the app has always started with.
 */
export function EnsureDefaults(): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2484002225);
}

export function ImportEntries(scope: domain$0.EnvScope, entries: dotenv$0.Entry[] | null): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2566995860, scope, entries);
}

/**
 * ParseDotenv reads a .env file for the import dialog's preview: what is in it, and which names
 * look like secrets. The dialog decides what to keep; parsing it is not the window's job.
 */
export function ParseDotenv(text: string): $CancellablePromise<dotenv$0.Entry[] | null> {
    return $Call.ByID(265416718, text);
}

export function RemoveVariable(scope: domain$0.EnvScope, id: string): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2903571973, scope, id);
}

/**
 * Reveal is the eye button: the only call that hands a secret's value to the window.
 */
export function Reveal(id: string): $CancellablePromise<string> {
    return $Call.ByID(510563592, id);
}

/**
 * Snapshot is the whole screen. Secret values are not in it: a secret says it has one, and Reveal
 * is what shows it.
 */
export function Snapshot(): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2070616517);
}

export function UpdateEnvironment(id: string, patch: environment$0.EnvironmentPatch): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2674046333, id, patch);
}

export function UpdateVariable(scope: domain$0.EnvScope, patch: environment$0.VariablePatch): $CancellablePromise<domain$0.EnvState> {
    return $Call.ByID(2299448532, scope, patch);
}
