// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Failure is a startup problem the frontend has to explain. It cannot be a dialog: a dialog needs
 * a running app, and the failures recorded here happen before one exists.
 */
export interface Failure {
    "kind": string;
    "message": string;
    "detail"?: string;
}

/**
 * StartupStatus is what the frontend reads on mount: whether the app has a database at all, and
 * where that database lives either way.
 */
export interface StartupStatus {
    "ready": boolean;
    "failure"?: Failure | null;
    "dataDir": string;
    "dbPath": string;
}
