// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * Failure is a startup problem the frontend has to explain. It cannot be a dialog: a dialog needs
 * a running app, and the failures recorded here happen before one exists.
 */
export interface Failure {
    "kind": string;
    "message": string;
    "detail"?: string;
}

/**
 * ResolvedVariable is what the token tooltip needs. It is a struct because a bound method may only
 * return a value and an error, and because "not found" is a normal answer rather than a failure.
 */
export interface ResolvedVariable {
    "found": boolean;
    "resolution": domain$0.Resolution;
}

/**
 * StartupStatus is what the frontend reads on mount: whether the app has a database at all, and
 * where that database lives either way.
 */
export interface StartupStatus {
    "ready": boolean;
    "failure"?: Failure | null;
    "dataDir": string;
    "dbPath": string;
}
