// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as draft$0 from "../../usecase/draft/models.js";

/**
 * CreatedCollection is CreatedNode for a collection rather than a request.
 */
export interface CreatedCollection {
    "collection": domain$0.Collection;
    "tree": domain$0.Collection[] | null;
}

/**
 * CreatedNode is what a creation answers with: the row that appeared and the tree it appeared in.
 * The id has to come back from Go — a lookup by name would find the older row of the same name.
 */
export interface CreatedNode {
    "node": domain$0.CollectionNode;
    "tree": domain$0.Collection[] | null;
}

/**
 * Failure is a startup problem the frontend has to explain. It cannot be a dialog: a dialog needs
 * a running app, and the failures recorded here happen before one exists.
 */
export interface Failure {
    "kind": string;

    /**
     * Detail is the error itself, for the screen to show under the sentence it writes for the kind.
     */
    "detail"?: string;
}

/**
 * MenuLabels are the few words the native menu needs. They arrive from the window, because the menu
 * is drawn by the system and only the page knows the language — the alternative would be a second
 * catalogue here, in one language, drifting away from the one the rest of the app reads.
 */
export interface MenuLabels {
    "about": string;
    "help": string;
    "checkUpdates": string;
}

/**
 * NodeEditor is assembled in this layer because this is the only one that knows both features —
 * collections own the tree, the draft owns the editing — and neither should know the other.
 */
export interface NodeEditor {
    "tree": domain$0.Collection[] | null;
    "node": domain$0.CollectionNode;
    "state": draft$0.State;
}

/**
 * StartupStatus is what the frontend reads on mount: whether the app has a database at all, and
 * where that database lives either way.
 */
export interface StartupStatus {
    "ready": boolean;
    "failure"?: Failure | null;
    "dataDir": string;
    "dbPath": string;
}
