// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecordsService is the history and the requests that fill it: sending one, reading what came back,
 * and forgetting what the retention rules no longer keep.
 * 
 * It holds the draft as well as the history, and this is the one place that does: a request is
 * composed by one feature and sent by another, and the layer that knows both is the layer that puts
 * them together.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as draft$0 from "../../usecase/draft/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as record$0 from "../../usecase/record/models.js";

/**
 * Body is the call a viewer makes for a body that did not travel with the record — either because
 * it is large or because the record arrived in a list. An absent side is an empty string, not an
 * error: "this request had no body" is an answer, not a failure.
 */
export function Body(id: string, side: domain$0.BodySide): $CancellablePromise<string> {
    return $Call.ByID(2604131729, id, side);
}

export function Cancel(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2510990271, id);
}

export function Clear(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(833468246, ids);
}

/**
 * ImportLegacy moves the history the old frontend kept in localStorage into the database, once. The
 * payload is the raw string: reading that shape is this side's job, not the window's.
 */
export function ImportLegacy(raw: string): $CancellablePromise<record$0.ImportReport> {
    return $Call.ByID(1457247847, raw);
}

/**
 * Ingest stores a record the app did not send. The extension has this already, through the bridge;
 * it is bound so the window can keep the sample it shows off with.
 */
export function Ingest($in: record$0.IngestInput): $CancellablePromise<domain$0.Record> {
    return $Call.ByID(1730945833, $in);
}

/**
 * List is what the panel draws: everything but the body text, so two hundred rows do not carry two
 * hundred documents and selecting one costs nothing until its body is opened.
 */
export function List(source: domain$0.RecordSource, limit: number): $CancellablePromise<domain$0.Record[] | null> {
    return $Call.ByID(2698898957, source, limit);
}

/**
 * Prune applies the retention rules now, which is what the settings screen does when the window is
 * shortened.
 */
export function Prune(): $CancellablePromise<number> {
    return $Call.ByID(446232403);
}

/**
 * Record is one record by id. A run's row names the record it produced, and this is how the window
 * opens it — the same thing a click on a history row does, for a row that is not in history.
 */
export function Record(id: string): $CancellablePromise<domain$0.Record> {
    return $Call.ByID(958301344, id);
}

/**
 * Send starts the request a draft holds and answers with its id at once. The draft is read here
 * rather than handed in: sending it means resolving its `{{tokens}}`, and a secret's value is on
 * this side of the boundary — handing the window a request to send would mean handing it the
 * secrets in it.
 * 
 * The id names which draft: the command line's, or the collection node whose card asked to send —
 * and sending a card's request does not save it, which is a gesture of its own.
 * 
 * What comes of the attempt arrives as an event, which is what lets the spinner belong to an id the
 * window can cancel.
 */
export function Send(draftID: domain$0.DraftID): $CancellablePromise<string> {
    return $Call.ByID(442880083, draftID);
}

/**
 * SendSpec starts a request that is not the one being composed — following a link out of a
 * response, which must not disturb the draft the user is typing in.
 */
export function SendSpec(seed: draft$0.Seed): $CancellablePromise<string> {
    return $Call.ByID(2929572836, seed);
}
