// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecordsService is the history and the requests that fill it: sending one, reading what came back,
 * and forgetting what the retention rules no longer keep.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as record$0 from "../../usecase/record/models.js";

/**
 * Body is the call a viewer makes for a body that did not travel with the record — either because
 * it is large or because the record arrived in a list. An absent side is an empty string, not an
 * error: "this request had no body" is an answer, not a failure.
 */
export function Body(id: string, side: domain$0.BodySide): $CancellablePromise<string> {
    return $Call.ByID(2604131729, id, side);
}

export function Cancel(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2510990271, id);
}

export function Clear(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(833468246, ids);
}

/**
 * ImportLegacy moves the history the old frontend kept in localStorage into the database, once. The
 * payload is the raw string: reading that shape is this side's job, not the window's.
 */
export function ImportLegacy(raw: string): $CancellablePromise<record$0.ImportReport> {
    return $Call.ByID(1457247847, raw);
}

/**
 * Ingest stores a record the app did not send. The extension has this already, through the bridge;
 * it is bound so the window can keep the sample it shows off with.
 */
export function Ingest($in: record$0.IngestInput): $CancellablePromise<domain$0.Record> {
    return $Call.ByID(1730945833, $in);
}

/**
 * List is what the panel draws: everything but the body text, so two hundred rows do not carry two
 * hundred documents and selecting one costs nothing until its body is opened.
 */
export function List(source: domain$0.RecordSource, limit: number): $CancellablePromise<domain$0.Record[] | null> {
    return $Call.ByID(2698898957, source, limit);
}

/**
 * Prune applies the retention rules now, which is what the settings screen does when the window is
 * shortened.
 */
export function Prune(): $CancellablePromise<number> {
    return $Call.ByID(446232403);
}

/**
 * Send starts a request and answers with its id at once. What comes of it arrives as an event, which
 * is what lets the spinner belong to an id the window can cancel.
 */
export function Send($in: record$0.SendInput): $CancellablePromise<string> {
    return $Call.ByID(442880083, $in);
}
