// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RequestsService sends what the request builder produces. It stays this thin on purpose: the
 * engine is where a request is actually sent, and the record it produces is written by the records
 * feature, not here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * CancelRequest stops whatever is in flight. It keeps its old name and its old meaning — the
 * window has one request at a time and cannot know an id — while the engine itself cancels by id.
 */
export function CancelRequest(): $CancellablePromise<void> {
    return $Call.ByID(2459867364);
}

export function Fetch(url: string, headers: { [_ in string]?: string } | null): $CancellablePromise<domain$0.Response | null> {
    return $Call.ByID(2177003683, url, headers);
}

export function SendRequest(method: string, url: string, headers: { [_ in string]?: string } | null, body: string): $CancellablePromise<domain$0.Response | null> {
    return $Call.ByID(2074924624, method, url, headers, body);
}
