// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptingService is the code of a collection as the window works with it: what a level runs of its
 * own, what runs around a node, and what the scripts of a record did.
 * 
 * It holds the feature itself and nothing else: a level's code, what runs around a node and what the
 * scripts of a record did are all questions the scripting feature answers, whoever the level belongs
 * to — a collection, a node of one, or the draft the command line is composing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scripting$0 from "../../usecase/scripting/models.js";

/**
 * Chain is what runs around a node, outermost first. The editor needs it to say what a level would
 * inherit: the code a person sees when their own script is empty is somebody else's.
 */
export function Chain(nodeID: string): $CancellablePromise<scripting$0.Level[] | null> {
    return $Call.ByID(1190212711, nodeID);
}

/**
 * Runs is what the scripts of one record did, in the order they ran. An empty answer is a request
 * nothing runs around, which is most of them.
 */
export function Runs(recordID: string): $CancellablePromise<domain$0.ScriptRun[] | null> {
    return $Call.ByID(1289978984, recordID);
}

/**
 * SaveScripts writes what a level has of its own, and nil puts it back to inheriting. The answer is
 * what was written, so the editor draws the state the database is in rather than the one it hoped for.
 */
export function SaveScripts(id: string, scripts: domain$0.Scripts | null): $CancellablePromise<domain$0.Scripts | null> {
    return $Call.ByID(1273721977, id, scripts);
}

/**
 * Scripts is what one level has of its own. Nil is "not set here" — the levels above are what runs —
 * and that is a different answer from a script that is simply empty.
 * 
 * A level no row has is read the same way: the editor opens on what is selected, the command line opens
 * before its draft is written, and neither is a failure to show code for.
 */
export function Scripts(id: string): $CancellablePromise<domain$0.Scripts | null> {
    return $Call.ByID(2823574710, id);
}
