// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService is the palette: one question, one answer, and no state kept between them. The window
 * asks on every pause in typing, so the call carries no id it would have to be matched against —
 * what is stale is decided by the window, which knows which question it is still waiting for.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "../../usecase/search/models.js";

export function Query($in: search$0.Query): $CancellablePromise<domain$0.SearchResult> {
    return $Call.ByID(3485809485, $in);
}
