// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the preferences the window reads at startup and writes as the user works.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../usecase/settings/models.js";

/**
 * SetCaptureFilters stores the rules the extension filters by. It does not hand them over: the
 * bridge is a different service, and the window calls it — one place to fail is not two.
 */
export function SetCaptureFilters(filters: domain$0.CaptureFilters): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(2877214555, filters);
}

/**
 * SetLanguage stores the choice and broadcasts it, the same way the theme is broadcast — and for
 * the same reason: no window is the one that tells the others.
 */
export function SetLanguage(language: domain$0.Language): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(2933980808, language);
}

export function SetLayout(patch: settings$0.LayoutPatch): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(3666996644, patch);
}

export function SetRetention(retention: domain$0.Retention): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(1214144256, retention);
}

/**
 * SetTheme stores the choice and broadcasts it, so every window follows — the About window is not
 * told by whoever changed it.
 */
export function SetTheme(theme: domain$0.Theme): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(817907931, theme);
}

/**
 * SetUpdateChannel stores which releases may be offered. A check already run keeps its answer on
 * screen until the next one asks the new channel.
 */
export function SetUpdateChannel(channel: domain$0.UpdateChannel): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(1307526778, channel);
}

/**
 * SetUpdateCheck stores whether the app may look for a release on its own. It broadcasts nothing:
 * the window that changed it draws the switch itself, and the next launch is what the preference
 * is for.
 */
export function SetUpdateCheck(auto: boolean): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(1861163125, auto);
}

export function Snapshot(): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(3127333622);
}
