// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService is the app talking about itself: what it is, what its window does, when it last
 * checked for a release, and whether it managed to open its own data.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../infra/updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Build is the CI run number, empty for local builds.
 */
export function Build(): $CancellablePromise<string> {
    return $Call.ByID(2938636118);
}

/**
 * CheckForUpdates answers the About window's own check. A release it finds is also announced to
 * the main window, so the status bar's link appears without waiting for the next launch — the
 * one place a manual check and the startup check have to agree.
 */
export function CheckForUpdates(): $CancellablePromise<updater$0.Info | null> {
    return $Call.ByID(2532603509);
}

export function Name(): $CancellablePromise<string> {
    return $Call.ByID(3613513165);
}

/**
 * OpenDataFolder shows the user where the database lives, which is the one useful action left
 * when it cannot be opened.
 */
export function OpenDataFolder(): $CancellablePromise<void> {
    return $Call.ByID(1158083454);
}

/**
 * RequestUpdateCheck reuses or opens the About window and asks it to run a check.
 */
export function RequestUpdateCheck(): $CancellablePromise<void> {
    return $Call.ByID(2298407682);
}

/**
 * RetryInit re-runs the startup step behind the failure screen's "Повторить" — the database may
 * have been locked, the disk full, the directory permissions wrong.
 */
export function RetryInit(): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(3094433782);
}

export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(2638395008);
}

/**
 * StartupStatus is what the frontend reads first: without a database there is nothing else to
 * show, and this is where it learns why.
 */
export function StartupStatus(): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(1841738245);
}

/**
 * TakeUpdateCheckRequest reports and clears a request parked by RequestUpdateCheck.
 */
export function TakeUpdateCheckRequest(): $CancellablePromise<boolean> {
    return $Call.ByID(2654636965);
}

export function ToggleMaximize(): $CancellablePromise<void> {
    return $Call.ByID(1279844260);
}

export function UpdateNow(version: string): $CancellablePromise<void> {
    return $Call.ByID(2526098225, version);
}

/**
 * UpdateStatus is what the last check saw, without touching the network.
 */
export function UpdateStatus(): $CancellablePromise<updater$0.Info | null> {
    return $Call.ByID(557022529);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(724317330);
}
