// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService is the app talking about itself: what it is, what its windows do, and whether it
 * managed to open its own data. Updating has a service of its own; everything that belongs to no
 * feature in particular stays here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyLanguage is the window handing over the words the native menu needs. The menu is drawn by
 * the system rather than by the page, and Go cannot resolve "system" — that is a question only the
 * webview can ask — so this is the one piece of the interface that is sent instead of read from the
 * catalogue.
 */
export function ApplyLanguage(labels: $models.MenuLabels): $CancellablePromise<void> {
    return $Call.ByID(2222094836, labels);
}

/**
 * Build is the CI run number, empty for local builds.
 */
export function Build(): $CancellablePromise<string> {
    return $Call.ByID(2938636118);
}

export function Name(): $CancellablePromise<string> {
    return $Call.ByID(3613513165);
}

/**
 * OpenDataFolder shows the user where the database lives, which is the one useful action left
 * when it cannot be opened.
 */
export function OpenDataFolder(): $CancellablePromise<void> {
    return $Call.ByID(1158083454);
}

/**
 * RetryInit re-runs the startup step behind the failure screen's "Повторить" — the database may
 * have been locked, the disk full, the directory permissions wrong.
 */
export function RetryInit(): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(3094433782);
}

export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(2638395008);
}

export function ShowSettings(): $CancellablePromise<void> {
    return $Call.ByID(1282847998);
}

/**
 * StartupStatus is what the frontend reads first: without a database there is nothing else to
 * show, and this is where it learns why.
 */
export function StartupStatus(): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(1841738245);
}

export function ToggleMaximize(): $CancellablePromise<void> {
    return $Call.ByID(1279844260);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(724317330);
}
