// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService is the app talking about itself: what it is, what its windows do, and whether it
 * managed to open its own data. Updating has a service of its own; everything that belongs to no
 * feature in particular stays here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyLanguage is the window handing over the words of the two surfaces Go draws but does not own:
 * the native menu, which the system draws, and the pages a sign-in puts in the browser. Neither can
 * be worded here — the catalogue is the window's, and Go cannot resolve "system", which is a
 * question only the webview can ask — so this is the one piece of the interface that is sent
 * instead of read. The two travel together because they are needed at the same two moments: as the
 * window mounts, and again whenever the language moves.
 */
export function ApplyLanguage(labels: $models.MenuLabels, pages: domain$0.SignInPages): $CancellablePromise<void> {
    return $Call.ByID(2222094836, labels, pages);
}

/**
 * Build is the CI run number, empty for local builds.
 */
export function Build(): $CancellablePromise<string> {
    return $Call.ByID(2938636118);
}

export function Name(): $CancellablePromise<string> {
    return $Call.ByID(3613513165);
}

/**
 * OpenDataFolder shows the user where the database lives, which is the one useful action left
 * when it cannot be opened.
 */
export function OpenDataFolder(): $CancellablePromise<void> {
    return $Call.ByID(1158083454);
}

/**
 * RetryInit re-runs the startup step behind the failure screen's "Retry" — the database may
 * have been locked, the disk full, the directory permissions wrong.
 */
export function RetryInit(): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(3094433782);
}

export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(2638395008);
}

/**
 * ShowSettings opens the preferences window. The category is the one to show — "account" for the
 * account menu — and an empty one leaves the window where it was, which is what the rail's gear
 * asks for.
 */
export function ShowSettings(category: string): $CancellablePromise<void> {
    return $Call.ByID(1282847998, category);
}

/**
 * StartupStatus is what the frontend reads first: without a database there is nothing else to
 * show, and this is where it learns why.
 */
export function StartupStatus(): $CancellablePromise<$models.StartupStatus> {
    return $Call.ByID(1841738245);
}

export function ToggleMaximize(): $CancellablePromise<void> {
    return $Call.ByID(1279844260);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(724317330);
}
