// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService is the update feature's whole surface towards a window: the About window and the
 * settings window check, the main window's status bar reads what the last check found, and the
 * update window installs it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../../usecase/update/models.js";

/**
 * Check runs a check the user asked for. Unlike the launch-time one it is never skipped and never
 * gated on the preference, and what it found is published to every window: without that the status
 * bar's link would not appear until the next launch.
 */
export function Check(): $CancellablePromise<update$0.Info> {
    return $Call.ByID(58428918);
}

/**
 * Install downloads the release and replaces the running binary. On success it does not return.
 */
export function Install(version: string): $CancellablePromise<void> {
    return $Call.ByID(3832038381, version);
}

/**
 * RequestCheck opens the About window and asks it to run a check. The menu and the rail both come
 * here: the request is parked as well as sent, because a window that does not exist yet has nothing
 * listening, and an open one never mounts again.
 */
export function RequestCheck(): $CancellablePromise<void> {
    return $Call.ByID(567297357);
}

/**
 * ShowWindow opens the window that describes a release and offers to install it.
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(1966802851);
}

/**
 * Skip records that the user does not want to hear about the version on screen again, answers with
 * what the app has to say now, and publishes it: the window that asked is about to close, and the
 * ones that stay open are showing the release it just dropped.
 */
export function Skip(): $CancellablePromise<update$0.Info> {
    return $Call.ByID(720813005);
}

/**
 * Status is what the last check saw, without touching the network: what a window opens on, and what
 * the status bar is rebuilt from after a restart.
 */
export function Status(): $CancellablePromise<update$0.Info> {
    return $Call.ByID(3826898008);
}

/**
 * TakeRequest reports and clears a check parked by RequestCheck. Destructive on purpose: both the
 * mount and the window's own button call it, and only the first may act on it.
 */
export function TakeRequest(): $CancellablePromise<boolean> {
    return $Call.ByID(2240740410);
}
