// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService is the switcher: which spaces exist, which one the window is showing, and what a
 * new one is called. Every call answers with the whole set, the way the environments and the tree
 * do — the window draws all of it at once, and a partial answer would only be a second thing to
 * keep.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../../usecase/workspace/models.js";

export function Create($in: workspace$0.CreateInput): $CancellablePromise<domain$0.WorkspaceState> {
    return $Call.ByID(2235692486, $in);
}

/**
 * Delete takes a workspace and everything in it. The one the app is born with is refused by the use
 * case, with a code the window words itself.
 */
export function Delete(id: string): $CancellablePromise<domain$0.WorkspaceState> {
    return $Call.ByID(662109293, id);
}

export function Snapshot(): $CancellablePromise<domain$0.WorkspaceState> {
    return $Call.ByID(1534920702);
}

/**
 * Switch points the app at another workspace. The data below the window is replaced by the caller:
 * this says which space is on screen, and the window reloads what that space holds.
 */
export function Switch(id: string): $CancellablePromise<domain$0.WorkspaceState> {
    return $Call.ByID(523197050, id);
}

export function Update(id: string, patch: workspace$0.Patch): $CancellablePromise<domain$0.WorkspaceState> {
    return $Call.ByID(3600006155, id, patch);
}
