// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BodyRef points at one side of a record: the text itself when it is small, otherwise its size and
 * a promise that the viewer can fetch it with a call of its own.
 */
export interface BodyRef {
    "inline"?: string;
    "size": number;
    "truncated"?: boolean;
}

/**
 * BodySide names one end of a record.
 */
export enum BodySide {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SideRequest = "request",
    SideResponse = "response",
};

/**
 * CookieRow is one row of the request-side jar the "Cookies" tab edits. Domain, path, expiry and
 * the flags are Set-Cookie attributes rather than parts of a request's own Cookie header; they are
 * kept so a draft can be restored from a record.
 */
export interface CookieRow {
    "name": string;
    "value": string;
    "domain"?: string;
    "path"?: string;
    "expires"?: string;
    "secure"?: boolean;
    "httpOnly"?: boolean;
}

/**
 * EnvScope names where a variable lives: one environment, or the globals that always apply.
 */
export interface EnvScope {
    /**
     * Environment is the environment's id; empty means the globals scope.
     */
    "environment"?: string;
}

/**
 * EnvState is everything the environments screen and the request preview need. Globals are the
 * scope that applies whatever the active environment is.
 */
export interface EnvState {
    "environments": Environment[] | null;
    "globals": Variable[] | null;

    /**
     * ActiveID is empty when no environment is selected.
     */
    "activeId"?: string;
}

/**
 * Environment is a named set of variables, one of which is active at a time.
 */
export interface Environment {
    "id": string;
    "name": string;
    "color"?: string;
    "readonly": boolean;
    "position": number;
    "vars": Variable[] | null;
}

/**
 * HeaderPair is one header line. Headers travel as a sequence rather than a map because the wire
 * allows a name to repeat — two Set-Cookie lines are two cookies — and a map would keep one.
 */
export interface HeaderPair {
    "name": string;
    "value": string;
}

/**
 * Record is a summary plus everything the response pane shows. The summary is embedded rather than
 * copied, so the two can never disagree about which request this is.
 */
export interface Record {
    "id": string;
    "source": RecordSource;
    "method": string;
    "url": string;
    "status": number;
    "statusText": string;
    "contentType"?: string;
    "error"?: string;
    "durationMs": number;
    "startedAt": number;

    /**
     * HasTiming separates "phases were measured" from "they all read zero": a captured request that
     * reused a connection has no connect phase, and one without the header has no phases at all.
     */
    "hasTiming"?: boolean;
    "tabId"?: number;
    "tabTitle"?: string;
    "tabURL"?: string;
    "favIconUrl"?: string;

    /**
     * Cancelled is the engine saying the user stopped this attempt. Nothing records such a request —
     * there is nothing to show for one — so it is false for everything history holds; it is here
     * because a record is the shape of an attempt, and that is one of the things an attempt can be.
     */
    "cancelled"?: boolean;
    "dnsMs"?: number;
    "connectMs"?: number;
    "tlsMs"?: number;
    "waitMs"?: number;
    "downloadMs"?: number;
    "requestBytes"?: number;
    "responseBytes"?: number;
    "requestHeaders": HeaderPair[] | null;
    "responseHeaders": HeaderPair[] | null;
    "requestCookies"?: CookieRow[] | null;
    "requestBody"?: BodyRef | null;
    "responseBody"?: BodyRef | null;
}

/**
 * RecordSource is where a record came from: the request builder or the browser extension. The two
 * are kept in one table because they are drawn by one list and compared in one place.
 */
export enum RecordSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceManual = "manual",
    SourceBrowser = "browser",
};

/**
 * Resolution is what a `{{token}}` resolves to, with where it came from so the tooltip can say it.
 */
export interface Resolution {
    "value"?: string;

    /**
     * "env" | "global"
     */
    "source": string;
    "kind": VariableKind;

    /**
     * HasValue is false when the value was withheld from the answer (a secret) or is empty.
     */
    "hasValue": boolean;
}

/**
 * Retention is how long history is kept. The count cap that has always applied stays: this is what
 * removes records by age on top of it.
 */
export enum Retention {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RetainWeek = "7",
    RetainMonth = "30",
    RetainForever = "forever",
};

/**
 * Settings is everything the app remembers about how it is set up, in the order the screen shows
 * it. Defaults live in one place — the use case's — so a fresh database and a missing row agree.
 */
export interface Settings {
    "theme": Theme;
    "inspectorOpen": boolean;
    "inspectorWidth": number;
    "sideWidth": number;
    "historyRetention": Retention;
}

/**
 * Theme is the user's choice; which palette it means is decided in the window, because "system" is
 * a question only the window can ask.
 */
export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeLight = "light",
    ThemeDark = "dark",
    ThemeSystem = "system",
};

/**
 * Variable is one `{{name}}` value. A secret's value is stored here like any other — the OS
 * keychain is gone, because it only ever worked on macOS — so masking is what keeps it out of
 * everything the user can see or copy.
 */
export interface Variable {
    "id": string;
    "name": string;
    "value"?: string;
    "kind": VariableKind;
    "enabled": boolean;
    "position": number;

    /**
     * HasValue says a value is stored even when Value is not sent — the snapshot never carries a
     * secret, and the sheet needs to know whether revealing it would show anything.
     */
    "hasValue": boolean;
}

/**
 * VariableKind separates a value that may be shown from one that must never leave the app
 * unmasked: exports, logs and the request preview all go through the mask.
 */
export enum VariableKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VariableText = "text",
    VariableSecret = "secret",
};
