// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvScope names where a variable lives: one environment, or the globals that always apply.
 */
export interface EnvScope {
    /**
     * Environment is the environment's id; empty means the globals scope.
     */
    "environment"?: string;
}

/**
 * EnvState is everything the environments screen and the request preview need. Globals are the
 * scope that applies whatever the active environment is.
 */
export interface EnvState {
    "environments": Environment[] | null;
    "globals": Variable[] | null;

    /**
     * ActiveID is empty when no environment is selected.
     */
    "activeId"?: string;
}

/**
 * Environment is a named set of variables, one of which is active at a time.
 */
export interface Environment {
    "id": string;
    "name": string;
    "color"?: string;
    "readonly": boolean;
    "position": number;
    "vars": Variable[] | null;
}

/**
 * HeaderPair is one header line. Headers travel as a sequence rather than a map because the wire
 * allows a name to repeat — two Set-Cookie lines are two cookies — and a map would keep one.
 */
export interface HeaderPair {
    "name": string;
    "value": string;
}

/**
 * Resolution is what a `{{token}}` resolves to, with where it came from so the tooltip can say it.
 */
export interface Resolution {
    "value"?: string;

    /**
     * "env" | "global"
     */
    "source": string;
    "kind": VariableKind;

    /**
     * HasValue is false when the value was withheld from the answer (a secret) or is empty.
     */
    "hasValue": boolean;
}

/**
 * Response is what a request comes back as: the body plus the per-phase timings.
 */
export interface Response {
    "status": number;
    "statusText": string;
    "headers": HeaderPair[] | null;
    "body": string;
    "durationMs": number;
    "contentType": string;
    "error"?: string;
    "cancelled"?: boolean;
    "dnsMs"?: number;
    "connectMs"?: number;
    "tlsMs"?: number;
    "waitMs"?: number;
    "downloadMs"?: number;

    /**
     * BodyTruncated says the body was cut at the engine's cap, so a viewer can say so instead of
     * showing half a document as if it were all of it.
     */
    "bodyTruncated"?: boolean;
}

/**
 * Retention is how long history is kept. The count cap that has always applied stays: this is what
 * removes records by age on top of it.
 */
export enum Retention {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RetainWeek = "7",
    RetainMonth = "30",
    RetainForever = "forever",
};

/**
 * Settings is everything the app remembers about how it is set up, in the order the screen shows
 * it. Defaults live in one place — the use case's — so a fresh database and a missing row agree.
 */
export interface Settings {
    "theme": Theme;
    "inspectorOpen": boolean;
    "inspectorWidth": number;
    "sideWidth": number;
    "historyRetention": Retention;
}

/**
 * Theme is the user's choice; which palette it means is decided in the window, because "system" is
 * a question only the window can ask.
 */
export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeLight = "light",
    ThemeDark = "dark",
    ThemeSystem = "system",
};

/**
 * Variable is one `{{name}}` value. A secret's value is stored here like any other — the OS
 * keychain is gone, because it only ever worked on macOS — so masking is what keeps it out of
 * everything the user can see or copy.
 */
export interface Variable {
    "id": string;
    "name": string;
    "value"?: string;
    "kind": VariableKind;
    "enabled": boolean;
    "position": number;

    /**
     * HasValue says a value is stored even when Value is not sent — the snapshot never carries a
     * secret, and the sheet needs to know whether revealing it would show anything.
     */
    "hasValue": boolean;
}

/**
 * VariableKind separates a value that may be shown from one that must never leave the app
 * unmasked: exports, logs and the request preview all go through the mask.
 */
export enum VariableKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VariableText = "text",
    VariableSecret = "secret",
};
