// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HeaderPair is one header line. Headers travel as a sequence rather than a map because the wire
 * allows a name to repeat — two Set-Cookie lines are two cookies — and a map would keep one.
 */
export interface HeaderPair {
    "name": string;
    "value": string;
}

/**
 * Response is what a request comes back as: the body plus the per-phase timings.
 */
export interface Response {
    "status": number;
    "statusText": string;
    "headers": HeaderPair[] | null;
    "body": string;
    "durationMs": number;
    "contentType": string;
    "error"?: string;
    "cancelled"?: boolean;
    "dnsMs"?: number;
    "connectMs"?: number;
    "tlsMs"?: number;
    "waitMs"?: number;
    "downloadMs"?: number;

    /**
     * BodyTruncated says the body was cut at the engine's cap, so a viewer can say so instead of
     * showing half a document as if it were all of it.
     */
    "bodyTruncated"?: boolean;
}
