// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is what a window is told about updating: the answer the last check produced, and where the
 * running build stands. One shape for the event, for the status read and for the About window's own
 * check, because the three are the same question asked from different places.
 */
export interface Info {
    "available": boolean;
    "current": string;
    "latest": string;
    "notes"?: string[] | null;
    "checkedAt"?: number;
}
