// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * Query is what the palette asks: the words typed, and the one area the user narrowed to.
 * 
 * No area is nil rather than an empty word, because that is what it is: a kind this build does not
 * know is a kind a newer window asked for, and it should search nothing rather than everything.
 * 
 * The rows a group draws are not a number here: how many fit under one heading is the answer's own
 * business, and the window should not have to know it.
 */
export interface Query {
    "text": string;
    "kind": domain$0.SearchKind | null;
}
