// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * LayoutPatch is a partial update of the panel geometry: a nil field is left as it is.
 */
export interface LayoutPatch {
    "inspectorOpen"?: boolean | null;
    "inspectorWidth"?: number | null;
    "sideWidth"?: number | null;
}

/**
 * ThemeChanged is what a window receives when the theme moves.
 */
export interface ThemeChanged {
    "theme": domain$0.Theme;
}
