// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function BridgePort() {
  return window['go']['main']['App']['BridgePort']();
}

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function Fetch(arg1, arg2) {
  return window['go']['main']['App']['Fetch'](arg1, arg2);
}

export function PauseCapture() {
  return window['go']['main']['App']['PauseCapture']();
}

export function ResumeCapture() {
  return window['go']['main']['App']['ResumeCapture']();
}

export function SecretDelete(arg1, arg2) {
  return window['go']['main']['App']['SecretDelete'](arg1, arg2);
}

export function SecretGet(arg1, arg2) {
  return window['go']['main']['App']['SecretGet'](arg1, arg2);
}

export function SecretSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['SecretSet'](arg1, arg2, arg3);
}

export function SendRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function UpdateNow(arg1) {
  return window['go']['main']['App']['UpdateNow'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
