// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jsonapi} from '../models';
import {update} from '../models';
import {main} from '../models';

export function Analyze(arg1:string):Promise<jsonapi.Analysis>;

export function CancelRequest():Promise<void>;

export function CheckForUpdates():Promise<update.Update>;

export function Fetch(arg1:string,arg2:Record<string, string>):Promise<main.ResponseResult>;

export function SendRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<main.ResponseResult>;

export function ShowAbout():Promise<void>;

export function ToggleMaximize():Promise<void>;

export function UpdateNow(arg1:string):Promise<void>;

export function Version():Promise<string>;
