// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";

/**
 * State is what a window needs to draw the account: whether anybody is signed in, and what is
 * happening right now — a sign-in in progress is a modal with a spinner, not an empty pane.
 */
export interface State {
    "signedIn": boolean;
    "account": domain$0.Account;

    /**
     * Waiting is a sign-in the app is in the middle of: the code is out, the browser is open, and
     * nothing has happened yet.
     */
    "waiting": boolean;
    "challenge": domain$0.Challenge;

    /**
     * Failure is why the last attempt came to nothing, in the app's own codes. The window words it.
     */
    "failure"?: domain$0.Failure | null;
}
